#############################################################################
# Makefile for building: yugioh
# Generated by qmake (2.01a) (Qt 4.8.7) on: Tue Mar 20 15:32:54 2018
# Project:  yugioh.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile yugioh.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++0x -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = app.cpp \
		generique.cpp \
		genProgress.cpp \
		intro.cpp \
		main.cpp \
		shadowButt.cpp \
		deckBuilding/deck.cpp \
		deckBuilding/carte.cpp \
		deckBuilding/carte_monstre.cpp \
		deckBuilding/carte_monstre_effet.cpp \
		deckBuilding/carte_monstre_normal.cpp \
		deckBuilding/bouton_ouvrir_fichier_deck.cpp \
		deckBuilding/carte_magie.cpp \
		deckBuilding/carte_piege.cpp \
		deckBuilding/editeur_de_carte.cpp moc_app.cpp \
		moc_generique.cpp \
		moc_genProgress.cpp \
		moc_intro.cpp \
		moc_main.cpp \
		moc_shadowButt.cpp \
		moc_bouton_ouvrir_fichier_deck.cpp \
		moc_editeur_de_carte.cpp
OBJECTS       = app.o \
		generique.o \
		genProgress.o \
		intro.o \
		main.o \
		shadowButt.o \
		deck.o \
		carte.o \
		carte_monstre.o \
		carte_monstre_effet.o \
		carte_monstre_normal.o \
		bouton_ouvrir_fichier_deck.o \
		carte_magie.o \
		carte_piege.o \
		editeur_de_carte.o \
		moc_app.o \
		moc_generique.o \
		moc_genProgress.o \
		moc_intro.o \
		moc_main.o \
		moc_shadowButt.o \
		moc_bouton_ouvrir_fichier_deck.o \
		moc_editeur_de_carte.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		yugioh.pro
QMAKE_TARGET  = yugioh
DESTDIR       = 
TARGET        = yugioh

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: yugioh.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile yugioh.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile yugioh.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/yugioh1.0.0 || $(MKDIR) .tmp/yugioh1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/yugioh1.0.0/ && $(COPY_FILE) --parents app.h generique.h genProgress.h intro.h main.h shadowButt.h sleeper.h deckBuilding/deck.h deckBuilding/carte_monstre.h deckBuilding/carte.h deckBuilding/carte_monstre_effet.h deckBuilding/carte_monstre_normal.h deckBuilding/bouton_ouvrir_fichier_deck.h deckBuilding/carte_magie.h deckBuilding/carte_piege.h deckBuilding/editeur_de_carte.h .tmp/yugioh1.0.0/ && $(COPY_FILE) --parents app.cpp generique.cpp genProgress.cpp intro.cpp main.cpp shadowButt.cpp deckBuilding/deck.cpp deckBuilding/carte.cpp deckBuilding/carte_monstre.cpp deckBuilding/carte_monstre_effet.cpp deckBuilding/carte_monstre_normal.cpp deckBuilding/bouton_ouvrir_fichier_deck.cpp deckBuilding/carte_magie.cpp deckBuilding/carte_piege.cpp deckBuilding/editeur_de_carte.cpp .tmp/yugioh1.0.0/ && (cd `dirname .tmp/yugioh1.0.0` && $(TAR) yugioh1.0.0.tar yugioh1.0.0 && $(COMPRESS) yugioh1.0.0.tar) && $(MOVE) `dirname .tmp/yugioh1.0.0`/yugioh1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/yugioh1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_app.cpp moc_generique.cpp moc_genProgress.cpp moc_intro.cpp moc_main.cpp moc_shadowButt.cpp moc_bouton_ouvrir_fichier_deck.cpp moc_editeur_de_carte.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_app.cpp moc_generique.cpp moc_genProgress.cpp moc_intro.cpp moc_main.cpp moc_shadowButt.cpp moc_bouton_ouvrir_fichier_deck.cpp moc_editeur_de_carte.cpp
moc_app.cpp: app.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) app.h -o moc_app.cpp

moc_generique.cpp: genProgress.h \
		sleeper.h \
		generique.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) generique.h -o moc_generique.cpp

moc_genProgress.cpp: sleeper.h \
		genProgress.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) genProgress.h -o moc_genProgress.cpp

moc_intro.cpp: shadowButt.h \
		sleeper.h \
		intro.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) intro.h -o moc_intro.cpp

moc_main.cpp: app.h \
		intro.h \
		shadowButt.h \
		sleeper.h \
		generique.h \
		genProgress.h \
		main.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) main.h -o moc_main.cpp

moc_shadowButt.cpp: sleeper.h \
		shadowButt.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) shadowButt.h -o moc_shadowButt.cpp

moc_bouton_ouvrir_fichier_deck.cpp: deckBuilding/bouton_ouvrir_fichier_deck.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) deckBuilding/bouton_ouvrir_fichier_deck.h -o moc_bouton_ouvrir_fichier_deck.cpp

moc_editeur_de_carte.cpp: deckBuilding/carte.h \
		deckBuilding/editeur_de_carte.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) deckBuilding/editeur_de_carte.h -o moc_editeur_de_carte.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

app.o: app.cpp app.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o app.o app.cpp

generique.o: generique.cpp generique.h \
		genProgress.h \
		sleeper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generique.o generique.cpp

genProgress.o: genProgress.cpp genProgress.h \
		sleeper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o genProgress.o genProgress.cpp

intro.o: intro.cpp intro.h \
		shadowButt.h \
		sleeper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o intro.o intro.cpp

main.o: main.cpp main.h \
		app.h \
		intro.h \
		shadowButt.h \
		sleeper.h \
		generique.h \
		genProgress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

shadowButt.o: shadowButt.cpp shadowButt.h \
		sleeper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shadowButt.o shadowButt.cpp

deck.o: deckBuilding/deck.cpp deckBuilding/deck.h \
		deckBuilding/carte.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o deck.o deckBuilding/deck.cpp

carte.o: deckBuilding/carte.cpp deckBuilding/carte.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o carte.o deckBuilding/carte.cpp

carte_monstre.o: deckBuilding/carte_monstre.cpp deckBuilding/carte_monstre.h \
		deckBuilding/carte.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o carte_monstre.o deckBuilding/carte_monstre.cpp

carte_monstre_effet.o: deckBuilding/carte_monstre_effet.cpp deckBuilding/carte_monstre_effet.h \
		deckBuilding/carte_monstre.h \
		deckBuilding/carte.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o carte_monstre_effet.o deckBuilding/carte_monstre_effet.cpp

carte_monstre_normal.o: deckBuilding/carte_monstre_normal.cpp deckBuilding/carte_monstre_normal.h \
		deckBuilding/carte_monstre.h \
		deckBuilding/carte.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o carte_monstre_normal.o deckBuilding/carte_monstre_normal.cpp

bouton_ouvrir_fichier_deck.o: deckBuilding/bouton_ouvrir_fichier_deck.cpp deckBuilding/bouton_ouvrir_fichier_deck.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bouton_ouvrir_fichier_deck.o deckBuilding/bouton_ouvrir_fichier_deck.cpp

carte_magie.o: deckBuilding/carte_magie.cpp deckBuilding/carte_magie.h \
		deckBuilding/carte.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o carte_magie.o deckBuilding/carte_magie.cpp

carte_piege.o: deckBuilding/carte_piege.cpp deckBuilding/carte_piege.h \
		deckBuilding/carte.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o carte_piege.o deckBuilding/carte_piege.cpp

editeur_de_carte.o: deckBuilding/editeur_de_carte.cpp deckBuilding/editeur_de_carte.h \
		deckBuilding/carte.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editeur_de_carte.o deckBuilding/editeur_de_carte.cpp

moc_app.o: moc_app.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_app.o moc_app.cpp

moc_generique.o: moc_generique.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_generique.o moc_generique.cpp

moc_genProgress.o: moc_genProgress.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_genProgress.o moc_genProgress.cpp

moc_intro.o: moc_intro.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_intro.o moc_intro.cpp

moc_main.o: moc_main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main.o moc_main.cpp

moc_shadowButt.o: moc_shadowButt.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_shadowButt.o moc_shadowButt.cpp

moc_bouton_ouvrir_fichier_deck.o: moc_bouton_ouvrir_fichier_deck.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bouton_ouvrir_fichier_deck.o moc_bouton_ouvrir_fichier_deck.cpp

moc_editeur_de_carte.o: moc_editeur_de_carte.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editeur_de_carte.o moc_editeur_de_carte.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

