######################################################################
# Automatically generated by qmake (2.01a) mer. 25. juin 14:54:55 2008
######################################################################

TEMPLATE = app
CONFIG += release
QT += network
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FenServeur.h
SOURCES += FenServeur.cpp main.cpp
